### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by BlueWoIf** [tothi/prosmart-mqtt#1]
Hi, i have encountered a problem where I try to start up the script but the prosmart website returns "No access.", even though i double checked the token and userid and tried multiple accounts and login types. Am I doing something wrong or it is just too old and never going to work again?

**Comment by tothi** [comment]
yep, this might not work now because they made some significant changes on their API and I have not used this since that change. btw, it would be much better to write a native addon instead of doing this MQTT stuff. so I won't going to update this, if I'll have some free cycles to look for the changes, I would try to implement an addon instead.
